### ISSUE TITLE
To include a twitter share option

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/HarmonyCode#12]
Currently we have the share options for following social sites, need to include twitter or X as well

<img width="867" alt="Screenshot 2023-10-03 at 6 20 57 PM" src="https://github.com/DhanushNehru/HarmonyCode/assets/22955675/f330d18b-7dac-4948-bc5d-769c18c80b09">

**Comment by Sha1kh4** [comment]
Hello, I see that the problem has been resolved, but the button is not visible on desktop yet it is when seen on a mobile devices.

on mobile:
![image](https://github.com/DhanushNehru/HarmonyCode/assets/117739824/12a546ec-5070-4417-aa76-98622d9a3945)


on desktop:
![image](https://github.com/DhanushNehru/HarmonyCode/assets/117739824/68bedd0e-759a-4b9d-be00-08a6828a527c)

**Comment by DhanushNehru** [comment]
Hi @Sha1kh4 you can create the issue , I will assign it to you 

Great find 👏

**Comment by Sha1kh4** [comment]
Done
