### ISSUE TITLE
Firebase Error while running dev server

### ISSUE THREAD

**Issue by RavindraP04** [DhanushNehru/HarmonyCode#19]
![image](https://github.com/DhanushNehru/HarmonyCode/assets/98400348/562fc61e-7e21-4053-b413-2902b18fba14)
---

The dev server is not running because of this error after running
`npm run dev`
that's why gitpod one is also not working

**Comment by RavindraP04** [comment]
@DhanushNehru Please add `hacktoberfest` tags in #14 (‘-’*)

**Comment by RavindraP04** [comment]
@DhanushNehru Please look into this

**Comment by DhanushNehru** [comment]
@RavindraP04  please check the latest readme, you need to setup the firebase
