### ISSUE TITLE
Fix UI: The Twitter(X) logo is not visible on desktop yet it is when seen on a mobile devices

### ISSUE THREAD

**Issue by Sha1kh4** [DhanushNehru/HarmonyCode#24]
The Twitter(X) logo/button is not visible on desktop yet it is when seen on a mobile devices.

on mobile:
![image](https://github.com/DhanushNehru/HarmonyCode/assets/117739824/12a546ec-5070-4417-aa76-98622d9a3945)

on desktop:
![image](https://github.com/DhanushNehru/HarmonyCode/assets/117739824/68bedd0e-759a-4b9d-be00-08a6828a527c)

**Comment by Sha1kh4** [comment]
hey @DhanushNehru  can you plz add hacktoberfest and hacktoberfest-accepted tags too, would help a lot

**Comment by Sha1kh4** [comment]
Thanks a lot @DhanushNehru .

**Comment by DhanushNehru** [comment]
Great work @Sha1kh4 . Thanks for your contribution
