### ISSUE TITLE
Add Login with Github feature

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/HarmonyCode#41]

**Comment by NohaFahmi** [comment]
Hi @DhanushNehru, can I work on this?

**Comment by ayush6678** [comment]
Hi @DhanushNehru, I would like to work on this issue. Can you assign this issue to me?

**Comment by j-mahapatra** [comment]
Created a PR with the desired changes. Please take a look.

**Comment by DhanushNehru** [comment]
Thanks @j-mahapatra
