### ISSUE TITLE
Github Sign-In Not Working

### ISSUE THREAD

**Issue by JeevaRamanathan** [DhanushNehru/HarmonyCode#47]
When attempting to sign in with GitHub, an error is encountered, specifically, "_Uncaught (in promise) FirebaseError: Firebase: Error (auth/operation-not-allowed)._"

**Possible Solution:** It is suggested to check the Firebase application's authentication settings. Ensure that the GitHub provider is added to the list of allowed sign-in methods. If it is not already added, including the GitHub provider can potentially resolve this issue.

**Comment by j-mahapatra** [comment]
Github provider needs to be added in firebase console. The step-by-step instructions can be found in firebase docs ([here](https://firebase.google.com/docs/auth/web/github-auth)).

**Comment by DhanushNehru** [comment]
Hi @JeevaRamanathan can you please update the readme as well , for people to be aware of using this sign in with GitHub feature

**Comment by JeevaRamanathan** [comment]
Hi @DhanushNehru, I have updated the readme and raised a PR ( #49 ), kindly check it
