### ISSUE TITLE
Include social icons

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/HarmonyCode#5]
Include social icons such as instagram, twitter in the footer of the page

**Comment by Aabiskar-dhenga** [comment]
hey dhanush can you elaborate where i should put social media icons >??

**Comment by DhanushNehru** [comment]
HI @Aabiskar-dhenga in the footer, but i think @Mirthhh08 is already working on it

**Comment by Mirthhh08** [comment]
![image](https://github.com/DhanushNehru/HarmonyCode/assets/92306499/ac24b495-78d9-4b6b-bbb5-414e79bbf4bf)
![image](https://github.com/DhanushNehru/HarmonyCode/assets/92306499/3fcb5c32-7d3b-46f3-b28c-5d247bc2c911)

Done with the work. A small request please add hacktoberfestaccepted tag .

**Comment by Mirthhh08** [comment]
if you want any changes please let me know!!

**Comment by DhanushNehru** [comment]
Can the 'Made with'  sentence be in the left itself. And only the social icons in the middle @Mirthhh08

**Comment by Mirthhh08** [comment]
![image](https://github.com/DhanushNehru/HarmonyCode/assets/92306499/7cc9f4b3-1e16-4045-a27c-bc355b90f426)
Please check it ones and then I'll raise the pull request

**Comment by DhanushNehru** [comment]
Hey @Mirthhh08 can you pull the latest code , as we have a share to social media in the footer .

Hope that doesn't collide

**Comment by Mirthhh08** [comment]
yeahh sure!!

**Comment by DhanushNehru** [comment]
Once done please raise a PR @Mirthhh08

**Comment by dhanyadgowda** [comment]
Hey @DhanushNehru if the issue is still there can u assign it to me
