### ISSUE TITLE
Incorporate sign in feature for this music site

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/HarmonyCode#8]
Incorporate sign in with google, github or any better way to access this site

**Comment by HarshMakadiya** [comment]
hey, can you assign this issue to me?

**Comment by suvraghosh** [comment]
Hi, Can you assign this to me.I love to do this work

**Comment by DhanushNehru** [comment]
Hi @suvraghosh , seems @HarshMakadiya is already working on it

**Comment by HarshMakadiya** [comment]
Hey @DhanushNehru, Thanks for assigning it to me. To summarize I have to implement sign-in using google, GitHub, etc. Right?

**Comment by DhanushNehru** [comment]
Yes, any one implementation would be fine, if you can do many sign in features it would be great @HarshMakadiya

**Comment by HarshMakadiya** [comment]
Okay sure! Let me check what I can do and I will get back to you if I have any further queries.

**Comment by suvraghosh** [comment]
@DhanushNehru Okay no problem.

**Comment by HarshMakadiya** [comment]
Hey, @DhanushNehru so currently I was thinking about implementing Google oAuth using Firebase will it be comfortable for you? Or like is there any other db you wanted to store login cred?

**Comment by DhanushNehru** [comment]
Yes sure go ahead @HarshMakadiya , but few things like configs, env etc .. hope it won't be directly hard-coded !

**Comment by HarshMakadiya** [comment]
@DhanushNehru Yes, I will keep in mind not to make it hard-coded.

**Comment by HarshMakadiya** [comment]
@DhanushNehru Thanks for letting me help on this project.

**Comment by NeerajReddyK** [comment]
@DhanushNehru

I wanna work on this. I have already worked on something similar. Could you assign this to me
