### ISSUE TITLE
Incorporate share feature for this site

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/HarmonyCode#9]
To incorporate a share feature so that people can share this site in social media

**Comment by ShashwatPS** [comment]
Hey @DhanushNehru interested to work on this issue if possible can you assign it to me ?

**Comment by Allan2000-Git** [comment]
@DhanushNehru Can I work on this issue? If yes, can you provide a brief description like where the share button must be, what link has to be shared (user specific or product link) etc.
